sudo: false

language: node_js

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/www/kerbit/.meteor:$PATH"

cache:
  directories:
    - node_modules

before_script:
  - meteor npm install

script:
  - meteor remove practicalmeteor:mocha
  - meteor add dispatch:mocha-phantomjs
  - meteor test --once --driver-package dispatch:mocha-phantomjs
  - meteor build $HOME/build.tgz
