sudo: false

language: node_js

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - node_modules

before_script:
  - echo $HOME 
  - echo $PATH
  - cd www/kerbit 
  - meteor npm install

script:
  - meteor test --once --driver-package dispatch:mocha-phantomjs
