sudo: false

language: node_js

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - node_modules

before_script:
  - cd www/kerbit 
  - meteor npm install
script:
  - meteor add dispatch:mocha-phantomjs
  - meteor test --once --driver-package dispatch:mocha-phantomjs
notifications:
  slack: curbit:deFtjCAGd3vlfhrJzEefCymO
  email: false
